# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_quickfinder.ui'
#
# Created: Wed Feb 27 14:09:46 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_quickFinder(object):
    def setupUi(self, quickFinder):
        quickFinder.setObjectName(_fromUtf8("quickFinder"))
        quickFinder.resize(328, 281)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setMargin(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.idButton = QtGui.QRadioButton(self.frame)
        self.idButton.setChecked(True)
        self.idButton.setObjectName(_fromUtf8("idButton"))
        self.buttonGroup = QtGui.QButtonGroup(quickFinder)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.idButton)
        self.gridLayout_3.addWidget(self.idButton, 2, 0, 1, 1)
        self.columnButton = QtGui.QRadioButton(self.frame)
        self.columnButton.setChecked(False)
        self.columnButton.setObjectName(_fromUtf8("columnButton"))
        self.buttonGroup.addButton(self.columnButton)
        self.gridLayout_3.addWidget(self.columnButton, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.fieldCombo = QtGui.QComboBox(self.frame)
        self.fieldCombo.setEnabled(False)
        self.fieldCombo.setObjectName(_fromUtf8("fieldCombo"))
        self.gridLayout_3.addWidget(self.fieldCombo, 2, 2, 1, 1)
        self.layerCombo = QtGui.QComboBox(self.frame)
        self.layerCombo.setObjectName(_fromUtf8("layerCombo"))
        self.gridLayout_3.addWidget(self.layerCombo, 0, 1, 1, 2)
        self.widget = QtGui.QWidget(self.frame)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.formLayout = QtGui.QFormLayout(self.widget_2)
        self.formLayout.setMargin(3)
        self.formLayout.setMargin(0)
        self.formLayout.setSpacing(3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.scaleBox = QtGui.QCheckBox(self.widget_2)
        self.scaleBox.setEnabled(False)
        self.scaleBox.setObjectName(_fromUtf8("scaleBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.scaleBox)
        self.selectBox = QtGui.QCheckBox(self.widget_2)
        self.selectBox.setEnabled(False)
        self.selectBox.setChecked(True)
        self.selectBox.setObjectName(_fromUtf8("selectBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.selectBox)
        self.panBox = QtGui.QCheckBox(self.widget_2)
        self.panBox.setEnabled(False)
        self.panBox.setObjectName(_fromUtf8("panBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.panBox)
        self.formBox = QtGui.QCheckBox(self.widget_2)
        self.formBox.setEnabled(False)
        self.formBox.setObjectName(_fromUtf8("formBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.formBox)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.goButton = QtGui.QPushButton(self.widget)
        self.goButton.setEnabled(False)
        self.goButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.gridLayout.addWidget(self.goButton, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 4, 0, 1, 3)
        self.idLine = QtGui.QLineEdit(self.frame)
        self.idLine.setEnabled(False)
        self.idLine.setObjectName(_fromUtf8("idLine"))
        self.gridLayout_3.addWidget(self.idLine, 3, 0, 1, 3)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        quickFinder.setWidget(self.dockWidgetContents)

        self.retranslateUi(quickFinder)
        QtCore.QObject.connect(self.idLine, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.goButton.click)
        QtCore.QObject.connect(self.columnButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fieldCombo.setEnabled)
        QtCore.QObject.connect(self.idButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fieldCombo.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(quickFinder)
        quickFinder.setTabOrder(self.goButton, self.selectBox)
        quickFinder.setTabOrder(self.selectBox, self.formBox)
        quickFinder.setTabOrder(self.formBox, self.panBox)
        quickFinder.setTabOrder(self.panBox, self.idLine)
        quickFinder.setTabOrder(self.idLine, self.scaleBox)
        quickFinder.setTabOrder(self.scaleBox, self.layerCombo)

    def retranslateUi(self, quickFinder):
        quickFinder.setWindowTitle(QtGui.QApplication.translate("quickFinder", "Quick Finder", None, QtGui.QApplication.UnicodeUTF8))
        self.idButton.setText(QtGui.QApplication.translate("quickFinder", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.columnButton.setText(QtGui.QApplication.translate("quickFinder", "Column", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("quickFinder", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleBox.setText(QtGui.QApplication.translate("quickFinder", "scale", None, QtGui.QApplication.UnicodeUTF8))
        self.selectBox.setText(QtGui.QApplication.translate("quickFinder", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.panBox.setText(QtGui.QApplication.translate("quickFinder", "pan", None, QtGui.QApplication.UnicodeUTF8))
        self.formBox.setText(QtGui.QApplication.translate("quickFinder", "open form", None, QtGui.QApplication.UnicodeUTF8))
        self.goButton.setText(QtGui.QApplication.translate("quickFinder", "Go", None, QtGui.QApplication.UnicodeUTF8))

